apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base/namespace-toolkit.yaml
  - base/toolkit-cluster-config.yaml
  - base/toolkit-console-link-job-rbac.yaml
  - base/toolkit-console-link-job-sa.yaml
  - base/turbonomic-t8c-operator-sa.yaml
  - base/turbonomic-t8c-operator-scc.yaml
