apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: turbonomic-t8c-operator-scc
spec:
  destination:
    namespace: turbonomic
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/turbonomic/t8c-operator-scc
    repoURL: https://github.com/mjperrins/tz-turbo-gitops-02
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
