apiVersion: v1
kind: Namespace
metadata:
  name: toolkit
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: toolkit-operator-group
  namespace: toolkit
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  targetNamespaces:
    - toolkit
---
